<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Academicdetail extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->library('session');
        $this->load->model('Academicdetail_model');
    }
    
    /*
     * Listing of academicdetails
     */
    function index()
    {
        $rollno = $this->session->userdata('rol');
        if($this->session->userdata('rol'))
        {
            $this->session->set_userdata('academic',$data);
   
        $data['academicdetails'] = $this->Academicdetail_model->get_academicdetails($rollno);
        $this->load->view('academicdetail/index',$data);
    }
    else
    {
    redirect('http://www.gnies.org');
    }

    }
    function academic($year = null,$month = null) {
    $this->load->model('Mycal_model');
    
   
  $data['calendar'] = $this->Mycal_model->generate($year,$month);
        
       
        $this->load-> view('personaldetail/calendar',$data);
       
    }
    
    /*
     * Adding new academicdetails
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rollno','Rollno','required|max_length[255]');
		$this->form_validation->set_rules('school','School','required|max_length[255]');
		$this->form_validation->set_rules('ssc','Ssc','required|integer');
		$this->form_validation->set_rules('intercollege','Intercollege','required|max_length[255]');
		$this->form_validation->set_rules('inter','Inter','required|integer');
		$this->form_validation->set_rules('Btechcollege','Btechcollege','required|max_length[255]');
		$this->form_validation->set_rules('percent','Percent','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'rollno' => $this->input->post('rollno'),
				'school' => $this->input->post('school'),
				'ssc' => $this->input->post('ssc'),
				'intercollege' => $this->input->post('intercollege'),
				'inter' => $this->input->post('inter'),
				'Btechcollege' => $this->input->post('Btechcollege'),
				'percent' => $this->input->post('percent'),
            );
            
            $academicdetails_id = $this->Academicdetail_model->add_academicdetails($params);
            redirect('academicdetail/index');
        }
        else
        {
            $this->load->view('academicdetail/add');
        }
    }
    
    /*
     * Editing academicdetails
     */
    function edit()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rollno','Rollno','required|max_length[255]');
		$this->form_validation->set_rules('school','School','required|max_length[255]');
		$this->form_validation->set_rules('ssc','Ssc','required|integer');
		$this->form_validation->set_rules('intercollege','Intercollege','required|max_length[255]');
		$this->form_validation->set_rules('inter','Inter','required|integer');
		$this->form_validation->set_rules('Btechcollege','Btechcollege','required|max_length[255]');
		$this->form_validation->set_rules('percent','Percent','required|integer');
		$rollno = $this->session->userdata('rol');
		if($this->form_validation->run())     
        {   
            $params = array(
				/*'rollno' => $this->input->post('rollno'),*/
				'school' => $this->input->post('school'),
				'ssc' => $this->input->post('ssc'),
				'intercollege' => $this->input->post('intercollege'),
				'inter' => $this->input->post('inter'),
				'Btechcollege' => $this->input->post('Btechcollege'),
				'percent' => $this->input->post('percent'),
            );

            $this->Academicdetail_model->update_academicdetails($rollno,$params);            
            redirect('academicdetail/index');
        }
        else
        {   
            $data['academicdetails'] = $this->Academicdetail_model->get_academicdetails($rollno);
            $this->load->view('academicdetail/edit',$data);
        }
    }
    
    /*
     
    function remove($aid)
    {
        $this->Academicdetail_model->delete_academicdetails($aid);
        redirect('academicdetail/index');
    }
    */
}
?>