 <?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        
         $this->load->model('Admin_model');
         $this->load->model('Personaldetail_model');
         $this->load->model('Project_model');
         $this->load->model('Academicdetail_model');
         $this->load->model('Resume_model');
         $this->load->model('Skillset_model');
        $this->load->library('session');
        $this->load->helper('form');
        
$this->load->library('form_validation');

        $this->load->library('table');
        $this->load->helper('url');
       
        
    }
    
   
    function index()
    {
    
    if(  $this->session->userdata('logged_in'))
           {
           $this->load->view('Admin/student');
           
             
        }
         else{
         
         redirect('http://www.gnies.org');
         }
       
        
    }
    
            
     
   public function services()
   {
   if(  $this->session->userdata('logged_in'))
           {
           $this->load->view('Admin/email');
           
             
        }
         else{
         
         redirect('http://www.gnies.org');
         }
  
   }
   
  public function sendmail(){
    $this->load->helper('url');

    $this->load->helper('email');
     $this->form_validation->set_rules('email', 'Email', 'trim|required|valid_email');
        $this->form_validation->set_rules('subject', 'Subject', 'trim|required');
 $this->form_validation->set_rules('message', 'Message', 'trim|required');
       
        if ($this->form_validation->run() == FALSE  )
                    {
                 $this->load->view('Admin/email');
        }
        else
        {

$this->load->library('email');
$config['protocol'] = 'sendmail';
$config['mailpath'] = '/usr/sbin/sendmail';


   
    $email = $this->input->post('email'); 
    $subject = $this->input->post('subject');
    $message = $this->input->post('message');   
  
      $this->email->from('placementhub@gnies.org' , 'Placement Hub');
      $this->email->to($email); 
      $this->email->subject($subject);
      $this->email->message($message);  
    
     
      if ($this->email->send())
         {
       echo "<script>alert('email has sent Successfully!');</script>";
          $this->load->view('Admin/email');  
           }
           else
           {
           echo "<script>alert('email has not sent!');</script>";
            $this->load->view('Admin/email');  
           }
   }
   $this->email->clear(TRUE);   

  }
 
    


/* End of file welcome.php */
/* Location: ./application/controllers/welcome.php */
   
    public function search() 
     {
     
     $this->load->helper('form');
 	$this->load->library('pagination');
 	$this->load->library('form_validation');
 
 	$pas = $this->input->post('branch');
   
        $ypas  = $this->input->post('ypass');


 	$config = array();
 	$config['base_url'] = base_url()."index.php/Admin/search/";
        $config['total_rows'] = $this->db->get('personaldetails')->num_rows();
        $config['per_page'] = "1000";
        $config["uri_segment"] = 3;
        $choice = $config["total_rows"] / $config["per_page"];
        $config["num_links"] =floor($choice);       
        //config for bootstrap pagination class integration
        $config['full_tag_open'] = '<ul class="pagination">';
        $config['full_tag_close'] = '</ul>';
        $config['first_link'] = 'First';
        $config['last_link'] = 'Last';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['prev_link'] = '&laquo';
        $config['prev_tag_open'] = '<li class="prev">';
        $config['prev_tag_close'] = '</li>';
        $config['next_link'] = '&raquo';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';

        $this->pagination->initialize($config);
     // $page = ($this->uri->segment($config["uri_segment"] )) ? $this->uri->segment($config["uri_segment"] ) : 0;
      
      
        $page = ($this->uri->segment(3));

   if(!empty($branch)) { 
				$search_keywords_array['branch'] =  $branch;
				$this->Admin_model->searchterm_handler('branch',$branch); 
			} else {
				$this->session->unset_userdata('branch');	
			}
			if(!empty($ypass)) { 
				$search_keywords_array['ypass'] =  $ypass;
				$this->Admin_model->searchterm_handler('ypass',$ypass);
			} else {
				$this->session->unset_userdata('ypass');	
			}
    
  /*$this->session->set_userdata('bran',$branch);
  $this->session->set_userdata('pass',$ypass);*/
 

  /* if($this->form_validation->run()== FALSE){
       
              $this->load->view('Admin/student');
            } 
            else
            {
            $params = array('branch'=>$this->session->userdata('bran'),
                            'ypass' => $this->session->userdata('pass'),
                            );
               */ 
                         
             $data["records"] = $this->Personaldetail_model->get_all_personaldetails($config["per_page"], $page);
             $data["pagination"] = $this->pagination->create_links();
       
$this->load->view('Admin/dis',$data); 
}   

    
 
           
              
    
      
   
    public function admin()
     {
  $this->load->helper('form');
 	
 	$this->load->library('form_validation');
  $this->form_validation->set_rules('username','Username','required');
  $this->form_validation->set_rules('password','Password','required');
   if($this->form_validation->run()== FALSE){
       
              $this->load->view('welcome_message');
            }
             else
              {
            
                $user = $this->input->post('username');
                $this->session->set_userdata('logged_in',$user);
                    $result = $this->Admin_model->admin();
                   
                if($result == TRUE)
                {
                     if( $this->session->userdata('logged_in'))
                       {
                         
                         $this->load->view('Admin/student'); 
         
                         } 
                     redirect('http://www.gnies.org');
                 
                 
                }
               
                   else{
                    echo "<script>
                    window.location.href='http://gnies.org/';
                    alert('Wrong Username or password!');
                    </script>";
                    
                        

                      
                    }
             
            }
                 
               
  
 }//login
 
 
public function rollno()
{
  $rollno = $this->input->post('rollno');
  $data['resume']= $this->Personaldetail_model->get_personaldetails($rollno);
  $data['acd'] = $this->Academicdetail_model->get_academicdetails($rollno);
  $data['proj'] = $this->Project_model->get_projects($rollno);
  $data['objective'] = $this->Resume_model->get_objective($rollno);
  $data['skills'] = $this->Skillset_model->get_skillset($rollno);
  $this->load->view('Admin/display',$data);
}

public function percentage()
{
 $this->load->helper('form');
 	$this->load->library('pagination');
 	$this->load->library('form_validation');
 
 	$pas = $this->input->post('branch');
   
        $ypas  = $this->input->post('ypass');


 	$config = array();
 	$config['base_url'] = base_url()."index.php/Admin/search/";
        $config['total_rows'] = $this->db->get('personaldetails')->num_rows();
        $config['per_page'] = "1000";
        $config["uri_segment"] = 3;
        $choice = $config["total_rows"] / $config["per_page"];
        $config["num_links"] =floor($choice);       
        //config for bootstrap pagination class integration
        $config['full_tag_open'] = '<ul class="pagination">';
        $config['full_tag_close'] = '</ul>';
        $config['first_link'] = 'First';
        $config['last_link'] = 'Last';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['prev_link'] = '&laquo';
        $config['prev_tag_open'] = '<li class="prev">';
        $config['prev_tag_close'] = '</li>';
        $config['next_link'] = '&raquo';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';

        $this->pagination->initialize($config);
        $page = ($this->uri->segment(3));
          $data["percentage"] = $this->Admin_model->get_percentage($config["per_page"], $page);
          $this->load->view('Admin/per',$data);
        
}
  
 }
    ?>