<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Personaldetail extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Personaldetail_model');
        $this->load->library('session');
       $this->load->helper(array('form', 'url'));

       
        
    }
    
    /*
     * Listing of personaldetails
     */
    function index()
    {
        $rollno = $this->session->userdata('rol');
        if($this->session->userdata('rol')) {
         $data['personaldetails'] = $this->Personaldetail_model->get_personaldetails($rollno);
         
        $this->load->view('personaldetail/index',$data);
        $this->session->set_userdata('personal',$data);
           } 
          else { 
           redirect('http://www.gnies.org');
           }
       
       
        
    }
    
    /*
     
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		$this->form_validation->set_rules('rollno','Rollno','required|max_length[255]');
		$this->form_validation->set_rules('branch','Branch','required|max_length[255]');
		$this->form_validation->set_rules('ypass','Ypass','required|integer');
		$this->form_validation->set_rules('email','Email','required|max_length[255]|valid_email');
		$this->form_validation->set_rules('phoneno','Phoneno','required|integer');
		$this->form_validation->set_rules('address','Address','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'rollno' => $this->input->post('rollno'),
				'branch' => $this->input->post('branch'),
				'ypass' => $this->input->post('ypass'),
				'email' => $this->input->post('email'),
				'phoneno' => $this->input->post('phoneno'),
				'address' => $this->input->post('address'),
            );
            
            $personaldetails_id = $this->Personaldetail_model->add_personaldetails($params);
            redirect('personaldetail/index');
        }
        else
        {
            $this->load->view('personaldetail/add');
        }
    }
    */
    /*
     * Editing personaldetails
     */
  function edit()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('name','Name','required|max_length[255]');
        $this->form_validation->set_rules('rollno','Rollno','required|max_length[255]');
        $this->form_validation->set_rules('branch','Branch','required|max_length[255]');
        $this->form_validation->set_rules('ypass','Ypass','required|integer|min_length[4]|max_length[5]');
        $this->form_validation->set_rules('email','Email','required|max_length[255]|valid_email');
        $this->form_validation->set_rules('phoneno','Phoneno','required|integer|min_length[10]|max_length[10]');
        $this->form_validation->set_rules('address','Address','required|max_length[255]');
        $rollno = $this->session->userdata('rol');
        if($this->form_validation->run())     
        { 
        
        $config = array(
                         'upload_path' => "./uploads/",
                         'allowed_types' => "gif|jpg|png|jpeg",
                         'overwrite' => TRUE,
                         'max_size' => "2048000", 
                         'max_height' => "5024",
                         'max_width' => "5680"
                        ); 
        
        
         $this->load->library('upload', $config);
       
          if ( $this->upload->do_upload('userfile'))
           {
            
             $path =  $this->upload->data(); 
            $params = array(
                'name' => $this->input->post('name'),
                'rollno' => $this->input->post('rollno'),
                'branch' => $this->input->post('branch'),
                'ypass' => $this->input->post('ypass'),
                'email' => $this->input->post('email'),
                'phoneno' => $this->input->post('phoneno'),
                'address' => $this->input->post('address'),
                'image'  => $path['file_name'],
            );


            $this->Personaldetail_model->update_personaldetails($rollno,$params);            
            redirect('personaldetail/index');
            }
            else{
             $error = array('error' => $this->upload->display_errors());
             echo $error['error'];
             }
               
        }
        else
        {   
            $data['personaldetails'] = $this->Personaldetail_model->get_personaldetails($rollno);
            $this->load->view('personaldetail/edit',$data);
        }
    }  
}
?>