<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Signup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Signup_model');
        $this->load->helper('form');
    }
    
    /*
     * Listing of signup
     */
    function index()
    {
       // $data['signup'] = $this->Signup_model->get_all_signup();
        $this->load->view('signup/index');
    }
    
    /*
     * Adding new signup
     */
     function changepwd()
     {
      $this->load->view('signup/forgotpassword');
     }
     
     function forgotpassword()
     {
      $this->load->library('form_validation');
        $this->form_validation->set_rules('email','Email','required|valid_email');
        if($this->form_validation->run())

        {
         
         $this->load->library('email');
$config['protocol'] = 'sendmail';
$config['mailpath'] = '/usr/sbin/sendmail';


   
    $emailid = $this->input->post('email'); 
    $subject = "Password change";
    $message ="please change your password here:http://www.gnies.org/index.php/Signup";   
  
      $this->email->from('placementhub@gnies.org' , 'Placement Hub');
      $this->email->to($emailid); 
      $this->email->subject($subject);
      $this->email->message($message);  
    
     
      if ($this->email->send())
         {
       /*echo "<script>alert('email has sent Successfully!');</script>";*/
        echo "<script>
alert('password reset link has sent to your email');
window.location.href='http://gnies.org';
</script>";
        // redirect('http://www.gnies.org');  
           }
           else
           {
           echo "<script>alert('email has not sent!');</script>";
           $this->load->view('signup/forgotpassword'); 
           }
        }
        else
        {
        $this->load->view('signup/forgotpassword');
        }
        
        
     }
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('rollno','Rollno','required|min_length[10]');
        $this->form_validation->set_rules('password','Password','required|max_length[25]');
		$this->form_validation->set_rules('password2','Password2','required|max_length[25]');
		
		
		if($this->form_validation->run())

        { 
         $rollno = $this->input->post('rollno');
       
         $exist =  $this->Signup_model->get_signup($rollno);
         
     
            $params = array(
				'password' => $this->input->post('password'),
				//'rollno' => $this->input->post('rollno'),
				
            );
            
            $signup = $this->Signup_model->update_signup($rollno,$params);
            
            
            redirect('http://gnies.org/');
       
       
        }
        else
        {
             
           
            $data['error'] = "please try again!";
            $this->load->view('signup/index',$data);
           

        }
    }
    
    /*
     
    function edit($rollno)
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|max_length[255]');
		$this->form_validation->set_rules('pid','Pid','required|integer');
		$this->form_validation->set_rules('image','Image','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'pid' => $this->input->post('pid'),
				'image' => $this->input->post('image'),
            );

            $this->Signup_model->update_signup($rollno,$params);            
            redirect('signup/index');
        }
        else
        {   
            $data['signup'] = $this->Signup_model->get_signup($rollno);
            $this->load->view('signup/edit',$data);
        }
    }
    
   
     */
    function remove($rollno)
    {
        $this->Signup_model->delete_signup($rollno);
        redirect('signup/index');
    }
}
?>