<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Skillset extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->library('session');
        $this->load->model('Skillset_model');
    }
    
    /*
     * Listing of skillset
     */
    function index()
    {
        $rollno = $this->session->userdata('rol');
        if($this->session->userdata('rol')) {
        $data['skillset'] = $this->Skillset_model->get_skillset($rollno);
        $this->load->view('skillset/index',$data);
        }
        else
        {
        redirect('http://www.gnies.org');
        }
    }
    
    /*
     * Adding new skillset
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('skill','Skill','required');
		$this->form_validation->set_rules('rollno','Rollno','required|max_length[255]');
        
		
		if($this->form_validation->run())     
        {    $rollno = $this->session->userdata('rol');

            $params = array(
				'skill' => $this->input->post('skill'),
				'rollno' => $this->input->post('rollno'),
                'level' => $this->input->post('level'),
               
            );
            
            $skillset_id = $this->Skillset_model->add_skillset($params);
            redirect('skillset/index');
        }
        else
        {
            $this->load->view('skillset/add');
        }
    }
    
    /*
     * Editing skillset
     */
    function edit($skillid)
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('skill','Skill','required');
		$this->form_validation->set_rules('rollno','Rollno','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'skill' => $this->input->post('skill'),
				'rollno' => $this->input->post('rollno'),
            );

            $this->Skillset_model->update_skillset($skillid,$params);            
            redirect('skillset/index');
        }
        else
        {   
            $data['skillset'] = $this->Skillset_model->get_skillset($skillid);
            $this->load->view('skillset/edit',$data);
        }
    }
    
    /*
     * Deleting skillset
     */
    function delete()
    {
        $skillid = $this->uri->segment(3);
        $this->Skillset_model->delete_skillset($skillid);
        redirect('skillset/index');
    }
}
?>