 <?php
 /*
This code is generated by Magic Code
Do not change any content if you are not confident. 
Author: Kumud Parajuli
URL: http://kumudparajuli.com.np
Email: magiccode@kumudparajuli.com.np
*/

 $this->load->view('template/header'); ?>
  <!-- Left side column. contains the logo and sidebar -->
  <?php $this->load->view('template/sidebar'); ?>
   <?php $this->load->view('template/navigation'); ?>
  <!-- Content Wrapper. Contains page content -->
  
  
 <?php $this->load->view($view); ?>
  
  
  <!-- /.content-wrapper -->
   <?php $this->load->view('template/footer'); ?>
