<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Academicdetail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
    
    /*
     * get academicdetails by aid
     */
    function get_academicdetails($rollno)
    {
        return $this->db->get_where('academicdetails',array('rollno'=>$rollno))->row_array();
    }
    
    /*
     * get all academicdetails
     */
    function get_all_academicdetails()
    {
        return $this->db->get('academicdetails')->result_array();
    }
    
    /*
     * function to add academicdetails
     */
    function add_academicdetails($params)
    {
        $this->db->insert('academicdetails',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update academicdetails
     */
    function update_academicdetails($rollno,$params)
    {
        $this->db->where('rollno',$rollno);
        $this->db->update('academicdetails',$params);
    }
    
    /*
     
    function delete_academicdetails($aid)
    {
        $this->db->delete('academicdetails',array('aid'=>$aid));
    }
    */
}
?>
