<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
 
class Achievements_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
   
    
    /*
     * get achievements by achid
     */
    function get_achievements($rollno)
    {
        return $this->db->get_where('achievements',array('rollno'=>$rollno))->result_array();
    }
    
    /*
     
    function get_all_achievements()
    {
        return $this->db->get('achievements')->result_array();
    }
    
    
    function add_achievements($params)
    {
        $this->db->insert('achievements',$params);
        return $this->db->insert_id();
    }
    
    
    function update_achievements($achid,$params)
    {
        $this->db->where('achid',$id);
        $this->db->update('achievements',$params);
    }
    
    
    function delete_achievements($achid)
    {
        $this->db->delete('achievements',array('achid'=>$achid));
    }
    */
}
?>