<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Personaldetail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
    
    /*
     * get personaldetails by pid
     */
    function get_personaldetails($rollno)
    {
      return $this->db->get_where('personaldetails',array('rollno'=>$rollno))->row_array();   
    }
    
   function all_details()
   {
   return $this->db->get('personaldetails')->result_array();  
   }
    
    function get_all_personaldetails($limit,$offset)
    {
                
                  
                   $pas = $this->input->post('branch');
   
                $ypas  = $this->input->post('ypass');
          $array =  array('branch'=>$pas,'ypass'=>$ypas);
      /*        
     $query = $this->db->select('*')
                       ->from('personaldetails')
                       ->where($array)
                       
                       ->get();
                                   
     
     return  $query->result_array();  
   
     */
    return  $this->db->get_where('personaldetails',$array, $limit)->result_array();
      }
      
      function count_results()
      {
        $pas = $this->input->post('branch');
   
                $ypas  = $this->input->post('ypass');
          $this->db->like('branch',$pas);
           $this->db->like('ypass',$ypas);
      return $this->db->count_all("personaldetails");
      }
    
     /* 
    function add_personaldetails($params)
    {
        $this->db->insert('personaldetails',$params);
        return $this->db->insert_id();
    }
    */
    
    /*
     * function to update personaldetails
     */
    function update_personaldetails($rollno,$params)
    {
        $this->db->where('rollno',$rollno);
        $this->db->update('personaldetails',$params);
    }
    
    /*
     
    function delete_personaldetails($rollno)
    {
        $this->db->delete('personaldetails',array('rollno'=>$rollno));
    }
    */
}
?>