<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Project_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
   
    
    /*
     * get projects by projectid
     */
    function get_projects($rollno)
    {
        return $this->db->get_where('projects',array('rollno'=>$rollno))->result_array();
    }

    function show_projects($id)
    {
        return $this->db->get_where('projects',array('projectid'=>$id))->result_array();
    }
    
    /*
     * get all projects
     */
    function get_all_projects($rollno)
    {
        return $this->db->get_where('projects',array('rollno'=>$rollno))->row_array();
    }
    
    /*
     * function to add projects
     */
    function add_projects($params)
    {
        $this->db->insert('projects',$params);
        return $this->db->insert_id();
    }
    
    

    function update_projects($projectid,$params)
    {
    
           echo $projectid;
        $this->db->where('projectid',$projectid);
        $this->db->update('projects',$params);
    }
    
    
     
    function delete_projects($id)
    {
        $this->db->delete('projects',array('projectid'=>$id));
    }
    
}
?>