<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Signup_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
  
    
   
     
    function get_signup($rollno)
    {
        return $this->db->get_where('signup',array('rollno'=>$rollno))->row_array();
    }
    
   /*
     
    function get_all_signup()
    {
        return $this->db->get('signup')->result_array();
    }
    
   
    function add_signup($params)
    {
        $this->db->insert('signup',$params);
        return $this->db->insert_id();
    }
    
    
     */
    function update_signup($rollno,$params)
    {
        $this->db->where('rollno',$rollno);
        $this->db->update('signup',$params);
    }
    
    /*
     * function to delete signup
     */
    function delete_signup($rollno)
    {
        $this->db->delete('signup',array('rollno'=>$rollno));
    }
}
?>