<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Skillset_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
    
    
    /*
     * get skillset by skillid
     */
    function get_skillset($rollno)
    {
        return $this->db->get_where('skillset',array('rollno'=>$rollno))->result_array();
    }
    
    /*
     * get all skillset
     */
    function get_all_skillset()
    {
        return $this->db->get('skillset')->result_array();
    }
    
    /*
     * function to add skillset
     */
    function add_skillset($params)
    {
      $query =  $this->db->insert('skillset',$params);
       return $this->db->insert_id(); 
    }
    
    /*
     * function to update skillset
     */
    function update_skillset($skillid,$params)
    {
        $this->db->where('skillid',$id);
        $this->db->update('skillset',$params);
    }
    
    /*
     * function to delete skillset
     */
    function delete_skillset($skillid)
    {
        $this->db->delete('skillset',array('skillid'=>$skillid));
    }
}
?>